Pagina inicial
SamaraRib/Projeto-Final-Web-Design pull request #1
Opened 2023-03-16 20:03 UTC by iamlzx7

Pagina Inicial

2023-03-17 02:14 UTC, SamaraRib requested changes
Tem que dar uma organizada nesse código para facilitar a leitura, várias tags no Index.html não estão alinhadas corretamente. Algumas partes do CSS também estão levemente desorganizadas. Seria bom remover o CSS inline e fazer tudo no CSS externo para não poluir o HTML

2023-03-17 02:14 UTC, SamaraRib commented on Index.html
> +             <img class="logo" src="Assets/IMG/imagem_2023-03-16_160906540-removebg-preview.png" alt="slaoq">
por que o alt está como "slaoq"?

2023-03-17 02:14 UTC, SamaraRib commented on Index.html
> +        <a href="nova iguaçu/index.html"><img src="Assets/IMG/mosaico.png" alt="mosaico"></a>
não acho que pôr as imagens do carrossel como links seja uma boa ideia, ele ainda funciona sem a tag a?

2023-03-17 02:14 UTC, SamaraRib commented on Index.html
> +        </div>
essas divs vazias tem alguma utilidade? não entendi pq elas estão aqui

2023-03-17 23:44 UTC, SamaraRib approved these changes

2023-03-18 00:13 UTC, loamijanu approved these changes

2023-03-18 00:16 UTC, Priscillaccampos20102 commented
ta ok

2023-03-18 00:19 UTC, marcellentavares approved these changes

2023-03-18 00:23 UTC, Priscillaccampos20102 approved these changes

2023-03-18 00:32 UTC, Hadryannaf approved these changes

2023-03-18 00:38 UTC, Otavioau approved these changes

2023-03-18 00:39 UTC, merged